/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Suro.Net.Client.Thrift
{
  public enum ResultCode
  {
    OK = 0,
    STOPPED = 1,
    CRC_CORRUPTED = 2,
    QUEUE_FULL = 3,
    OTHER_ERROR = 4,
  }
}
